project:
  type: book
  output-dir: docs
toc: false
book:
  title: "Amelia Henry"
  search: false
  
  # CHAPTERS/STRUCTURE 
  chapters:
  ## HOME 
    - index.qmd

  ## WORKFLOW
    - part: "Workflows"
      chapters:
      - posts/workflow_research.qmd
    - part: "Analyses"
    - part: "Plots"
    - part: "Tables"
    - part: "Reporting"
    - part: "Projects"
      # chapters:
      #   - posts/project_setup.qmd
  

## APPEARANCE 
syntax-highlighting: pygments

format:
  html:
    theme: 
      - minty
    code-copy: true
  
