project:
  type: book
toc: false
book:
  title: "Amelia Henry"
  search: false
  
  # CHAPTERS/STRUCTURE 
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Workflows"
      chapters:
        - posts/project_setup.qmd
  

## APPEARANCE 
syntax-highlighting: pygments

format:
  html:
    theme: 
      - custom.css
    code-copy: true
  pdf:
    documentclass: scrreprt



